title: Chaldea
description: Planning your servants, items and events.
github:
  is_project_page: false
show_downloads: false
theme: jekyll-theme-cayman
#remote-theme: huxpro/huxpro.github.io

permalink: /:categories/:title.html

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

